
[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[general]
import = ["~/.config/alacritty/local.toml"]

[window]
blur = true
opacity = 0.6
startup_mode = "Maximized"
padding = { x = 4, y = 4 }

[keyboard]
