#+TITLE: Emacs Configuration
#+AUTHOR: Shota Senga
#+EMAIL: shota@senta.me
#+OPTIONS: toc:nil num:nil
#+STARTUP: content

* Reference
:PROPERTIES:
:VISIBILITY: showall
:END:

- https://github.com/abo-abo/oremacs
- https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org
- https://github.com/danielmai/.emacs.d/blob/master/config.org
- https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org
- https://ladicle.com/post/config/
- https://github.com/zzamboni/dot-emacs/blob/master/init.org
- https://git.trevdev.ca/trevdev/dotfiles/src/commit/4b684ba5877278aee0d3d6a2e1dea51ed5df6898/emacs/configuration.org
- https://github.com/bzg/dotemacs/blob/master/emacs.org
- [[https://github.com/emacs-tw/awesome-emacs#jump-to-definition][emacs-tw/awesome-emacs]]
- https://github.com/daviwil/dotfiles/blob/master/Emacs.org

* Install

This configuration is for Emacs version 27, or avobe. Although most part work with older version, =jsx= doesn't.

#+begin_src sh
brew tap daviderestivo/emacs-head
brew install emacs-head --with-cocoa --with-imagemagick --with-jansson --HEAD
#+end_src


* Boot

Define utility variables for the rest of config.

#+begin_src emacs-lisp
(setq my--is-macos (eq system-type 'darwin))
(setq my--is-linux (eq system-type 'gnu/linux))
#+end_src


* Package Loader

Use =use-package= to configure packages and always ensure install the packages. Read [[https://jwiegley.github.io/use-package/keywords/][the doc]] for each keywords.

#+begin_src emacs-lisp
(eval-when-compile
  (require 'use-package)
  (require 'use-package-ensure)
  (setq use-package-always-ensure t))

(require 'diminish)
(require 'bind-key)
#+end_src

Always compile packages, and use the newest version available.

#+begin_src emacs-lisp
(use-package auto-compile
  :config (auto-compile-on-load-mode))

(setq load-prefer-newer t)
#+end_src

You can try package without isntallation!

#+begin_src emacs-lisp
(use-package try
  :ensure t)
#+end_src


* Apparence

** Font

Use =Hack= as the default font, =Hiragino= for Japanese. It seems [[https://ladicle.com/post/config/#gui-font][there is a way]] to make all font fammily align well.

#+begin_src emacs-lisp
(when window-system
  (setq use-default-font-for-symbols nil)

  (when my--is-macos
    (setq
     mac-option-key-is-meta t
     mac-option-modifier 'meta
     mac-command-key-is-meta t
     mac-command-modifier 'meta)
    (set-face-attribute 'default nil :font "Jetbrains Mono" :height 140))

  (if my--is-linux
      (set-face-attribute 'default nil :font "Hack-11"))

  (set-fontset-font nil
                    'japanese-jisx0208
                    (font-spec :family "Hiragino Kaku Gothic ProN"))
  (setq face-font-rescale-alist '(("Hiragino Kaku Gothic ProN" . 1.0))))
#+end_src

** Window

Run if Emacs runs with =window-system=

#+begin_src emacs-lisp
(when window-system
  ;; hide tool bars
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)

  ;; enter full screen
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; frame title
  (setq frame-title-format '(buffer-file-name "%f" ("%b")))

  ;; transparency
  (set-frame-parameter nil 'alpha 95)
  )
#+end_src

** Theme

My theme of choise is =doom-dracula= which looks better with high contrast compare to dracula original one.

#+begin_src emacs-lisp
(use-package doom-themes
  :custom
  (doom-themes-enable-italic t)
  (doom-themes-enable-bold t)
  :config
  (load-theme 'doom-dracula t)
  (doom-themes-org-config))
#+end_src

** Modeline

I picked =moody= modeline with some tweak.

#+begin_src emacs-lisp
(use-package moody
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode)
  (let ((line (face-attribute 'mode-line :underline)))
    (when my--is-linux
      (set-face-attribute 'mode-line          nil :font "Hack-11")
      (set-face-attribute 'mode-line-inactive nil :font "Hack-11"))

    (when my--is-macos
      (set-face-attribute 'mode-line          nil :font "Hack-11")
      (set-face-attribute 'mode-line-inactive nil :font "Hack-11"))

    (set-face-attribute 'mode-line          nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :underline  line)
    (set-face-attribute 'mode-line          nil :box        nil)
    (set-face-attribute 'mode-line          nil :background "#64729F")
    (set-face-attribute 'mode-line-inactive nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :foreground "#626262")
    (set-face-attribute 'mode-line-inactive nil :background "#40424E"))
  :custom
  (moody-mode-line-height 26))
#+end_src

** Small adjustments

Show symbols to indicate empty lines.

#+begin_src emacs-lisp
(toggle-indicate-empty-lines)
#+end_src

Don't show line numbers. Show column numbers.

#+begin_src emacs-lisp
;; (global-linum-mode 0)
(setq column-number-mode t)
;; (setq linum-format "%5d ")
#+end_src


* Global Interface

** Which Key

=which-key= shows keybindings that follows your input.

#+begin_src emacs-lisp
(use-package which-key
  :diminish
  :config
  (setq which-key-idle-delay 0.4)
  (setq inhibit-compacting-font-caches nil) ;; https://github.com/justbur/emacs-which-key/issues/130#issuecomment-416299329
  (which-key-mode))
#+end_src

** Window Control

Resize window with =M-<ARROW>=.

#+begin_src emacs-lisp
(global-set-key (kbd "M-<up>") 'enlarge-window)
(global-set-key (kbd "M-<down>") 'shrink-window)
(global-set-key (kbd "M-<left>") 'enlarge-window-horizontally)
(global-set-key (kbd "M-<right>") 'shrink-window-horizontally)
#+end_src

Jump around the windows with =ace-window=. The package provides ways to swiching and manuplating "other windows".

#+begin_src emacs-lisp
(use-package ace-window
  :diminish
  :bind ("C-c C-;" . ace-window)
  :config
  (setq aw-keys '(?a ?s ?d ?f ?j ?k ?l ?\;))
  (set-face-attribute
   'aw-leading-char-face nil
   :foreground "deep sky blue"
   :weight 'bold
   :height 3.0))
#+end_src

| key               | what                |
| =C-c C-;=         | Activate ace-window |
| =C-u C-c C-;=     | Swap window         |
| =C-u C-u C-c C-;= | Delete window       |

** Avy (switched from ace-jump)

=avy-goto-char-timer= accepts arbitrary number of characters as it's input. This is much more convinient than just one character idnex.

#+begin_src emacs-lisp
(use-package avy
  :diminish
  :bind ("C-;" . avy-goto-char-timer)
  :config
  (setq avy-timeout-seconds 0.3))
#+end_src

** Cursor and Region

Multiple cursors.

#+begin_src emacs-lisp
(use-package multiple-cursors
  :diminish
  :init
  (global-unset-key (kbd "M-<down-mouse-1>"))
  :bind (("C->" . 'mc/mark-next-like-this)
         ("C-<" . 'mc/mark-previous-like-this)
         ("C-:" . 'mc/edit-lines)
         ("M-<mouse-1>" . 'mc/add-cursor-on-click)
         ;; TODO these keybindings are conflicting with =outline-promote/demote=
         ("C-c C-<" . 'mc/mark-all-like-this)
         ("C-c C->" . 'mc/edit-lines)))
#+end_src

Expand region.

#+begin_src emacs-lisp
(use-package expand-region
  :bind (("C-2" . 'er/expand-region)
         ("C-@" . 'er/contract-region)))
#+end_src

As for rectangle manuplation, Emac has many commands built-in. [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Rectangles.html][See the doc]].

** keybinding Enhancement

Redo

/TODO: try undo-tree or download redo+ source/
https://www.emacswiki.org/emacs/RedoPlus

#+begin_src emacs-lisp
(use-package redo+
  :diminish
  :bind ("C-?" . redo)
  :config
  (setq undo-no-redo t))
#+end_src

Search text in region.

#+begin_src emacs-lisp
(defadvice isearch-mode
    (around isearch-mode-default-string
            (forward &optional regexp op-fun recursive-edit word-p) activate)
  (if (and transient-mark-mode mark-active (not (eq (mark) (point))))
      (progn
        (isearch-update-ring (buffer-substring-no-properties (mark) (point)))
        (deactivate-mark)
        ad-do-it
        (if (not forward)
            (isearch-repeat-backward)
          (goto-char (mark))
          (isearch-repeat-forward)))
    ad-do-it))
#+end_src

C-h to backspace

#+begin_src emacs-lisp
(global-set-key (kbd "C-h") 'delete-backward-char)

;; overrides mark-whole-buffer
(global-set-key (kbd "C-x h") 'help-for-help)
#+end_src

** Hungry Delete

#+begin_src emacs-lisp
(use-package hungry-delete
  :config
  (add-to-list 'hungry-delete-except-modes 'minibuffer-mode)
  :hook
  (after-init . global-hungry-delete-mode))
#+end_src

** Beacon

#+begin_src emacs-lisp
(use-package beacon
  :hook
  (after-init . beacon-mode))
#+end_src

** TODO Japanese Input with Mozc
=emacs-mozc= is conflicting with =fcitx-mozc=.
https://wiki.archlinux.org/index.php/Mozc

# #+begin_src emacs-lisp
# (use-package mozc
#   :if (eq system-type 'gnu/linux)
#   :config
#   (setq default-input-method "japanese-mozc")
#   ;; (setq mozc-candidate-style 'overlay)
# )
# #+end_src

** ivy (+ counsel swiper)

TODO: consider bind some more commands

- ivy-push-view
- ivy-pop-view
- counsel-rg (counsel-git-grep is covered by Projectile)
- ivy-resume
- counsel-bookmark
- counsel-descbinds
- counsel-outline
- counsel-org-file

TODO: How do I select actions for selected buffers/files?
I wanna do kill/delete selected items like Helm's =helm-select-action=.
see https://github.com/abo-abo/swiper/wiki/Copy,-move-and-delete-file-actions-for-counsel-find-file

TIP: Press =M-n= on swiper inserts a "thing" at point (=swiper-isearch-thing-at-point=)

#+begin_src emacs-lisp
(use-package counsel
  :diminish ivy-mode counsel-mode
  :hook
  (after-init . ivy-mode)

  :config
  ;; (use-package flx)
  ;; (use-package smex)
  (ivy-mode t)
  (setq ivy-use-virtual-buffers t
        ivy-count-format "(%d/%d) "
        ivy-height 15
        ivy-initial-inputs-alist nil
        )
  ;; prefer unordered search
  (setq ivy-re-builders-alist
        '((swiper . ivy--regex-plus)
          (swiper-isearch . ivy--regex-plus)
          (counsel-rg . ivy--regex-plus)
          (t . ivy--regex-fuzzy)))

  :bind
  (("M-x" . 'counsel-M-x)
   ;; ("C-x C-b" .  'ivy-switch-buffer)
   ("C-x C-f" .  'counsel-find-file)
   ("C-s" . 'swiper-isearch)
   ("C-r" . 'swiper-isearch-backward)
   ("C-c s" . 'isearch-forward-regexp)
   ("M-y" . 'counsel-yank-pop)
   ("<f1> f" . 'counsel-describe-function)
   ("<f1> v" . 'counsel-describe-variable)
   ("<f2> i" . 'counsel-info-lookup-symbol)
   ("<f2> u" . 'counsel-unicode-char)
   ("<f2> j" . 'counsel-set-variable)

   :map ivy-minibuffer-map
   ;; TODO this doesn't work with Swiper .. so I need to use =C-'= (default keybinding) instead
   ("C-;" . 'ivy-avy)))
#+end_src

- =ivy-rich= prettify ivy mini-buffer.
- =amex= prioritalize =M-x=.
- =flx= provide more flexible fuzzy search. (I found [[https://oremacs.com/2016/01/06/ivy-flx/][a blog post]] by the author of =ivy=)

#+begin_src emacs-lisp
(use-package amx :diminish :after counsel)
(use-package flx :diminish :after counsel)
(use-package ivy-rich
  :diminish
  :after counsel
  :config 
  (ivy-rich-mode t))
#+end_src

** ibuffer

#+begin_src emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

** Origami

Immitate the keybind form =vscode= to fold/unfold code blocks. /I should try and compare other packages/.

#+begin_src emacs-lisp
(use-package origami
  :hook ((prog-mode web-mode) . origami-mode)
  :bind (:map origami-mode-map
               ("M-s-[" . origami-close-node)
               ("M-s-]" . origami-show-node)))
#+end_src

* Dashboard

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :init
  (setq dashboard-banner-logo-title "Welcome to Emacs Dashboard")
  (setq dashboard-startup-banner 'logo)
  (setq dashboard-center-content t)
  (setq dashboard-show-shortcuts nil)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons nil)
  (setq dashboard-set-navigator t)
  (setq dashboard-set-footer nil)
  (setq dashboard-items '((recents  . 5)
                          (bookmarks . 5)
                          (projects . 5)
                          (agenda . 5)
                          (registers . 5)))
  :config
  (dashboard-setup-startup-hook))
#+end_src

* File Management

Prefer files move to the trash.

#+begin_src emacs-lisp
(setq  delete-by-moving-to-trash t)
(if (eq system-type 'darwin)
    (setq trash-directory "~/.Trash"))
#+end_src

** Dired

#+begin_src emacs-lisp
(setq dired-listing-switches "-aBhl  --group-directories-first")
#+end_src

* Programming

** Parenceis

Highlight matched parenceis

#+begin_src emacs-lisp
(show-paren-mode t)
#+end_src

Enable =rainbow-delimiters= for =prog-mode=, not only lispish language.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :diminish
  :hook (prog-mode . rainbow-delimiters-mode)
  :config
  (eldoc-add-command 'paredit-backward-delete
                     'paredit-close-round))
#+end_src

** Git

Magit for Git.

#+begin_src emacs-lisp
(use-package magit
  :bind ("C-x g" . magit-status)
  :config
  (setq magit-completing-read-function 'ivy-completing-read))
#+end_src

Show changed lines.

#+begin_src emacs-lisp
(use-package git-gutter
  :diminish
  :config (global-git-gutter-mode t))
#+end_src

** Snippets

The snippets are not include in the repo. By now, I use [[https://github.com/AndreaCrotti/yasnippet-snippets][AndreaCrotti/yasnippet-snippets]] by cpyoing the files under =.snippets= directory.

#+begin_src emacs-lisp
(use-package yasnippet
  :diminish
  :config
  (yas-global-mode 1))
#+end_src

** Project Management

Due to better integration with =ivy=, use =counsel-projectile= insstead. The package provides [[https://github.com/ericdanan/counsel-projectile#summary-of-interactive-commands][some more commands]].

#+begin_src emacs-lisp
(use-package counsel-projectile
  :hook
  (after-init . counsel-projectile-mode)
  :bind-keymap
  ("C-c p" . projectile-command-map) 
  :config
  (setq projectile-sort-order 'recently-active
        counsel-projectile-switch-project-action 'dired)
)
#+end_src

TIP: Newer version of =Projectile= knows about modern project files like =package.json= and =Pipfile= even though it's not documented. The definition is listed as =projectile-project-types=.

** Auto Complition


TODO: see this to improve complition
https://git.trevdev.ca/trevdev/dotfiles/src/commit/4b684ba5877278aee0d3d6a2e1dea51ed5df6898/emacs/configuration.org?lang=cs-CZ#company-auto-complete

#+begin_src emacs-lisp
(use-package company
  :diminish
  :hook
  (after-init . global-company-mode)
  :bind
  (("TAB" . company-indent-or-complete-common)
   ("C-." . company-complete-common)
   :map company-active-map
   ("C-n" . company-select-next)
   ("C-p" . company-select-previous)
   ("<tab>" . company-complete-common-or-cycle)
   :map company-search-map
   ("C-p" . company-select-previous)
   ("C-n" . company-select-next))
  :defines
  (company-dabbrev-ignore-case company-dabbrev-downcase)
  :custom
  (company-idle-delay 0)
  (company-echo-delay 0)
  (company-minimum-prefix-length 3))
#+end_src

Enhance =company-mode= with icons. You need to run ~all-the-icons-install-fonts~ to install icons.

/From [[https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-company.el][the author of company-box]]/

#+begin_src emacs-lisp
(use-package all-the-icons)
(use-package company-box
  :diminish
  :hook (company-mode . company-box-mode)
  :init (setq company-box-backends-colors nil
              company-box-show-single-candidate t
              company-box-max-candidates 50
              company-box-doc-delay 0.5)
  :config
  (with-no-warnings
    ;; Highlight `company-common'
    (defun my-company-box--make-line (candidate)
      (-let* (((candidate annotation len-c len-a backend) candidate)
              (color (company-box--get-color backend))
              ((c-color a-color i-color s-color) (company-box--resolve-colors color))
              (icon-string (and company-box--with-icons-p (company-box--add-icon candidate)))
              (candidate-string (concat (propertize (or company-common "") 'face 'company-tooltip-common)
                                        (substring (propertize candidate 'face 'company-box-candidate)
                                                   (length company-common) nil)))
              (align-string (when annotation
                              (concat " " (and company-tooltip-align-annotations
                                               (propertize " " 'display `(space :align-to (- right-fringe ,(or len-a 0) 1)))))))
              (space company-box--space)
              (icon-p company-box-enable-icon)
              (annotation-string (and annotation (propertize annotation 'face 'company-box-annotation)))
              (line (concat (unless (or (and (= space 2) icon-p) (= space 0))
                              (propertize " " 'display `(space :width ,(if (or (= space 1) (not icon-p)) 1 0.75))))
                            (company-box--apply-color icon-string i-color)
                            (company-box--apply-color candidate-string c-color)
                            align-string
                            (company-box--apply-color annotation-string a-color)))
              (len (length line)))
        (add-text-properties 0 len (list 'company-box--len (+ len-c len-a)
                                         'company-box--color s-color)
                             line)
        line))
    (advice-add #'company-box--make-line :override #'my-company-box--make-line)

    ;; Prettify icons
    (defun my-company-box-icons--elisp (candidate)
      (when (derived-mode-p 'emacs-lisp-mode)
        (let ((sym (intern candidate)))
          (cond ((fboundp sym) 'Function)
                ((featurep sym) 'Module)
                ((facep sym) 'Color)
                ((boundp sym) 'Variable)
                ((symbolp sym) 'Text)
                (t . nil)))))
    (advice-add #'company-box-icons--elisp :override #'my-company-box-icons--elisp))

  (when (and (display-graphic-p)
             (require 'all-the-icons nil t))
    (declare-function all-the-icons-faicon 'all-the-icons)
    (declare-function all-the-icons-material 'all-the-icons)
    (declare-function all-the-icons-octicon 'all-the-icons)
    (setq company-box-icons-all-the-icons
          `((Unknown . ,(all-the-icons-material "find_in_page" :height 0.85 :v-adjust -0.2))
            (Text . ,(all-the-icons-faicon "text-width" :height 0.8 :v-adjust -0.05))
            (Method . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.05 :face 'all-the-icons-purple))
            (Function . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.05 :face 'all-the-icons-purple))
            (Constructor . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.05 :face 'all-the-icons-purple))
            (Field . ,(all-the-icons-octicon "tag" :height 0.8 :v-adjust 0 :face 'all-the-icons-lblue))
            (Variable . ,(all-the-icons-octicon "tag" :height 0.8 :v-adjust 0 :face 'all-the-icons-lblue))
            (Class . ,(all-the-icons-material "settings_input_component" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-orange))
            (Interface . ,(all-the-icons-material "share" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-lblue))
            (Module . ,(all-the-icons-material "view_module" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-lblue))
            (Property . ,(all-the-icons-faicon "wrench" :height 0.8 :v-adjust -0.05))
            (Unit . ,(all-the-icons-material "settings_system_daydream" :height 0.85 :v-adjust -0.2))
            (Value . ,(all-the-icons-material "format_align_right" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-lblue))
            (Enum . ,(all-the-icons-material "storage" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-orange))
            (Keyword . ,(all-the-icons-material "filter_center_focus" :height 0.85 :v-adjust -0.2))
            (Snippet . ,(all-the-icons-material "format_align_center" :height 0.85 :v-adjust -0.2))
            (Color . ,(all-the-icons-material "palette" :height 0.85 :v-adjust -0.2))
            (File . ,(all-the-icons-faicon "file-o" :height 0.85 :v-adjust -0.05))
            (Reference . ,(all-the-icons-material "collections_bookmark" :height 0.85 :v-adjust -0.2))
            (Folder . ,(all-the-icons-faicon "folder-open" :height 0.85 :v-adjust -0.05))
            (EnumMember . ,(all-the-icons-material "format_align_right" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-lblue))
            (Constant . ,(all-the-icons-faicon "square-o" :height 0.85 :v-adjust -0.05))
            (Struct . ,(all-the-icons-material "settings_input_component" :height 0.85 :v-adjust -0.2 :face 'all-the-icons-orange))
            (Event . ,(all-the-icons-octicon "zap" :height 0.8 :v-adjust 0 :face 'all-the-icons-orange))
            (Operator . ,(all-the-icons-material "control_point" :height 0.85 :v-adjust -0.2))
            (TypeParameter . ,(all-the-icons-faicon "arrows" :height 0.8 :v-adjust -0.05))
            (Template . ,(all-the-icons-material "format_align_center" :height 0.85 :v-adjust -0.2)))
          company-box-icons-alist 'company-box-icons-all-the-icons)))
#+end_src

** Jump to definition

=Dumb Jump= just works in most of the cases! If you need more acculate solution, use LSP (just enable =eglot=) or =GNU Global=.

#+begin_src emacs-lisp
(use-package dumb-jump
  :diminish
  :bind
  (("M-." . dumb-jump-go))
  :config
  (setq dumb-jump-selector 'ivy))
#+end_src

Install =ggtags= for GNU Global.

TODO: Does =ivy= support TAGS?
- https://github.com/syohex/emacs-counsel-gtags
- https://www.reddit.com/r/emacs/comments/5453d4/what_does_your_ivyswiper_configuration_look_like/d7zejp8/
- You can find my old configuration with =helm= [[https://github.com/senta/.dotfiles/blob/b8dd3eb0d562f23820ae4deab7a4455a3315fee1/common/emacs.d/legacy.el#L681][here]].

#+begin_src emacs-lisp
(use-package ggtags :disabled)
#+end_src

** Indentation Highlight

I preffer having indent highlight especially for Python. It works a bit odd though.

#+begin_src emacs-lisp
(use-package highlight-indent-guides
  :disabled
  ;; :disabled
  :hook (prog-mode . highlight-indent-guides-mode)
  :custom
  (highlight-indent-guides-method 'character)
  (highlight-indent-guides-responsive 'stack)
  ;; (highlight-indent-guides-character ?\x678)
  (highlight-indent-guides-character ?\x2307)
)
#+end_src

** Restclient

#+begin_src emacs-lisp
(use-package restclient
  :mode
  ("\\.http\\'" . restclient-mode)
  ("\\.restclient" . restclient-mode))
#+end_src

* Programming/Markup Languages

** Scheme
I need these settings to enjoy SICP. But first of all, you need to have =scheme=. You can install it by running ~brew info mit-scheme~ for Mac or ~sudo apt install mit-scheme~ for Linux.

1. open a scheme file =*.scm=
2. Launch Scheme REPL by =M-x run-geiser=
3. enjoy!

=C-M-x= to evaluate the current line. =C-c-M-e= to evaluate on the REPL.

Here is the cheet-sheet for =Geiser=. See also: [[https://medium.com/@joshfeltonm/setting-up-emacs-for-sicp-from-scratch-daa6473885c5][Setting up Emacs for SICP from Scratch]].


#+begin_src emacs-lisp
(use-package geiser
  :config
  (setq geiser-mit-binary "/usr/local/bin/scheme"
        geiser-active-implementations '(mit)))
#+end_src


** Language Server Protocol

I use =eglot= as the front-end of LSP. You need to install language server for each language. See  [[https://github.com/joaotavora/eglot#connecting-to-a-server][eglot doc]] for the details.

#+begin_src emacs-lisp
(use-package eglot :defer t)
#+end_src

** Front-end

TODO: use /current/ version which defined on =~/.config/nvm/version=

#+begin_src emacs-lisp
;; TODO: why won't this line executed?
(add-to-list 'exec-path "~/.config/nvm/12.14.0/bin")
#+end_src

*** Prettier

Set up =Prettier= for code fomatting. This requires =Prettier= executable. You can install it by running ~npm install -g~. 

/Keep this section top to define reusable function for a keybinding./

#+begin_src emacs-lisp
(defun my-bind-prettier-js ()
  (local-set-key (kbd "C-M-\\") 'prettier-js))

(use-package prettier-js
  :commands prettier-js)
  ;; :hook (prettier-js-mode . (lambda ()
  ;;                          (local-set-key (kbd "C-M-\\") prettier-js))))
#+end_src

Some projects I'm currently working on doesn't use =Prettier=, so I cannot enable auto formatting hook globally. You can enable the hook with [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][Directory Variables]]. Put the code below in =.dir-locals.el=.

#+begin_example
((js-mode . ((eval . (prettier-js-mode t))))
 (web-mode . ((eval . (prettier-js-mode t)))))
#+end_example

*** Markup

#+begin_src emacs-lisp
(use-package web-mode
  :mode
  ("\\.html\\'"
   "\\.phtml\\'"
   "\\.tpl.php\\'"
   "\\.jsp\\'"
   "\\.as[cp]x\\'"
   "\\.erb\\'"
   "\\.mustache\\'"
   "\\.djhtml\\'"
   "\\.blade.php\\'" ;; move this under PHP
   "\\.ejs\\'"
   "\\.vue\\'"
   "\\.jinja2\\'"
   "\\.j2\\'"
   "\\.tpl\\'"
   "\\.tag\\'")
  ;; :hook (web-mode . #'my-bind-prettier-js)
  :config
  ;; engine
  (setq web-mode-engines-alist
        '(("php"    . "\\.phtml\\'")
          ("php"    . "\\.blade.php\\'")
          ("django" . "\\.jinja\\")
          ("django" . "\\.jinja2\\")
          ("django" . "\\.j2\\")
          ("ruby"  . "\\.erb\\'")))

  ;; face
  (set-face-attribute 'web-mode-html-tag-face nil :foreground "gray")

  ;; indentation
  (setq web-mode-markup-indent-offset 2
        web-mode-enable-auto-indentation nil
        web-mode-css-indent-offset 2
        web-mode-code-indent-offset 2
        web-mode-indent-style 2
        web-mode-script-padding 0
        web-mode-style-padding 0
        web-mode-block-padding 0))
#+end_src

#+begin_src emacs-lisp
(use-package emmet-mode
  :hook (css-mode web-mode sgml-mode js-jsx-mode)
  :config
  (setq emmet-self-closing-tag-style " /"
        emmet-move-cursor-between-quotes t))
#+end_src

#+begin_src emacs-lisp
(use-package pug-mode
  :mode ("\\.pug\\'" "\\.jade\\'"))
#+end_src

*** TypeScript

For TypeScript, I use [[https://github.com/ananthakumaran/tide][tide]] instead of eglot due to better TSX support. It requires =typescript= installed globally before using.

#+begin_src sh
npm install -g typescript
#+end_src

As it's documented, I need to define a function to share it in some modes.

#+begin_src emacs-lisp
(defun setup-tide-mode ()
  "Activate tide-mode"
  (interactive)
  (my-bind-prettier-js)
  (tide-setup)
  (flycheck-mode t)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode t)
  (tide-hl-identifier-mode t)
  (company-mode t))
#+end_src

Use =typescript-mode= as the major mode for TS.

#+begin_src emacs-lisp
(use-package typescript-mode
  :mode ("\\.ts\\'")
  :config
  (setq typescript-indent-level 2))

;; I get max-lisp-eval-depth error with =:hook=. So use add-hook instead.
;; (add-hook 'typescript-mode-hook #'setup-tide-mode)
#+end_src

#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
;; enable typescript-tslint checker
;; (flycheck-add-mode 'typescript-tslint 'web-mode)
#+end_src

And finally, enable tide for =typescript-mode= and =web-mode=.

#+begin_src emacs-lisp
(use-package tide
  :after (typescript-mode js-mode company flycheck))
  ;; :hook ((typescript-mode . tide-setup)
  ;;        (typescript-mode . tide-hl-identifier-mode)))
#+end_src

*** JavaScript

Emacs 27 has grate support of JSX built-in!! Using it with =tide= is a thing.

#+begin_src emacs-lisp
;; (add-hook 'js-mode-hook #'setup-tide-mode)
;; configure javascript-tide checker to run after your default javascript checker
;; (flycheck-add-next-checker 'javascript-eslint 'javascript-tide 'append)
;; prevent eslint check command: eslint --print-config .
;;https://github.com/suonlight/.emacs.d/blob/8f9b8a2aa6fc7a38d2b97b0b0c0a6acecf676a65/core/lang-js.el
;; (advice-add 'flycheck-eslint-config-exists-p :override (lambda() t))
;;(add-to-list 'auto-mode-alist "\\.js\\'" . js-jsx-mode)
;;(add-to-list 'auto-mode-alist "\\.jsx\\'" . js-jsx-mode)
#+end_src

*** TSX, JSX

=typescript-mode= doesn't support TSX. So I need to mix it with =web-mode=. (As for JavaScript, =js-mode= supports JSX in Emacs 27.)

#+begin_src emacs-lisp
;; (use-package web-mode
;;   :mode ("\\.tsx\\'")
;;   :hook (web-mode . (lambda ()
;;                       (when (string-equal "tsx" (file-name-extension buffer-file-name))
;;                         (setup-tide-mode)))))

;; TODO: enable linter, maybe
;; (flycheck-add-mode 'typescript-tslint 'web-mode) ; tsx
;; (flycheck-add-mode 'javascript-eslint 'web-mode) ; jsx
;; (flycheck-add-next-checker 'javascript-eslint 'jsx-tide 'append)
#+end_src

*** Vue

It doesn't work ... Use =web-mode= until I find workaround.

# Vue provides own LSP. However, eglot needs one LSP for one major-mode. So define =vue-mode= as an alias of =web-mode=. (Also see this https://github.com/joaotavora/eglot/issues/47)

# #+begin_src emacs-lisp
# (use-package web-mode
#   :after eglot
#   :config
#   (define-derived-mode vue-mode web-mode "Vue")
#   (add-to-list 'auto-mode-alist '("\\.vue\\'" . vue-mode))
#   (add-to-list 'eglot-server-programs '(vue-mode . ("vls"))))
# (add-hook 'web-mode-hook #'my-bind-prettier-js)
# #+end_src

*** TODO ESLint

setup with Flycheck

*** CSS/SCSS

#+begin_src emacs-lisp
(use-package css-mode
  :config
  (setq css-indent-offset 2))
;; (add-to-list 'company-backends 'company-css))
#+end_src

#+begin_src emacs-lisp
(use-package scss-mode
  :mode ("\\.scss\\'" "\\.sass\\'")
  :config
  (setq scss-compile-at-save nil)
  (add-to-list 'company-backends 'company-css))
#+end_src

#+begin_src emacs-lisp
(use-package less-css-mode :mode "\\.less\\'")
#+end_src

** Python

#+begin_src emacs-lisp
(use-package python-mode
  :defer t
  :config
  ;; And add the path to executables.
  (add-to-list 'exec-path "~/.pyenv/shims"))
#+end_src

You need to install =pls= to use =eglot= for LSP. (see [[https://github.com/palantir/python-language-server][the doc]])

#+begin_src sh
pip install python-language-server 'python-language-server[all]'
#+end_src

** C/C++

You need to install =ccls= to use =eglot= for LSP. (see [[https://github.com/MaskRay/ccls][the doc]])

#+begin_src emacs-lisp
(use-package google-c-style
  :hook ((c-mode-common . google-set-c-style)
         (c-mode-common . 'google-make-newline-indent)))
#+end_src

** Lisp

Define a list of lisp-ish modes to have the same configuration for the modes.
TODO: This may slows down Emacs launch

#+begin_src emacs-lisp
(setq my--lispish-modes '(clojure-mode emacs-lisp-mode lisp-interaction-mode
                                       lisp-mode scheme-mode))
#+end_src

I found =paredit= useful. But, it has very unique keybindings. For the later reference, you can look at below.

- [[http://pub.gajendra.net/src/paredit-refcard.pdf][Cheat sheet (PDF)]]
- [[http://www.daregada.sakuraweb.com/paredit_tutorial_ja.html][日本語チュートリアル]]

TODO: [[https://github.com/abo-abo/lispy][lispy]] seems worth take a look

#+begin_src emacs-lisp
(eval `(use-package paredit
         :hook (,my--lispish-modes . paredit-mode)))
#+end_src

And, .. enable =eldoc=.

#+begin_src emacs-lisp
(use-package eldoc
  :hook (emacs-lisp-mode . eldoc-mode))
#+end_src

Add a keybind for formatting a whole buffer in lisp.

#+begin_src emacs-lisp
(eval `(use-package srefactor
         :hook (,my--lispish-modes
                . (lambda ()
                    (require 'srefactor-lisp)
                    (local-set-key (kbd "C-M-\\") #'srefactor-lisp-format-buffer)))))
#+end_src

TODO: Try [[https://github.com/joaotavora/sly][SLY]] and/or [[https://common-lisp.net/project/slime/][SLIME]]

** PHP

#+begin_src emacs-lisp
(use-package php-mode
  :defer t
  :after eglot
  :config
  (add-to-list 'eglot-server-programs
               (cons 'php-mode (list "php" (expand-file-name "~/.composer/vendor/bin/php-language-server.php")))))
#+end_src

You need to install =pls= to use =eglot= for LSP. (see [[https://github.com/felixfbecker/php-language-server][the doc]])

#+begin_src sh
composer global require felixfbecker/language-server
composer global run-script --working-dir=$HOME/.composer/vendor/felixfbecker/language-server parse-stubs
#+end_src

/2019/12/28: PHP LSP doesn't work for some function, go to the definition for example./

** Ruby

#+begin_src emacs-lisp
(use-package ruby-mode
  :mode
  ("\\.rake\\'"
   "\\.gemspec\\'"
   "Rakefile"
   "Gemfile"
   "Capfile"
   "Vagrantfile"
   "Berksfle"))
#+end_src

#+begin_src emacs-lisp
(use-package ruby-end)
#+end_src

TODO: look at thoes configurtions for more useful config
https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org#ruby-and-rspec

** Go

You need to install =gopls= to use =eglot= for LSP. (see [[https://github.com/golang/tools/blob/master/gopls/README.md][the doc]])

#+begin_src emacs-lisp
(use-package go-mode
  :bind (:map go-mode-map
              ("C-c C-n" . go-run)
              ("C-c ."   . go-test-current-test)
              ("C-c f"   . go-test-current-file)
              ("C-c a"   . go-test-current-project))
  :config
  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook #'gofmt-before-save))
#+end_src

TODO: look at thoes configurtions for more useful config
https://ladicle.com/post/config/#golang
https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org#golang

** Rust

You need to install the Rust Language Server to use =eglot= for LSP. (see [[https://github.com/rust-lang/rls][the doc]])

#+begin_src sh
rustup update
rustup component add rls rust-analysis rust-src
#+end_src

#+begin_src emacs-lisp
(use-package rust-mode
  :config
  ;; (add-to-list 'exec-path "~/.cargo/bin")
  (setq rust-format-on-save t))
#+end_src

** Fish

#+begin_src emacs-lisp
(use-package fish-mode :defer t)
#+end_src

** JSON

#+begin_src emacs-lisp
(use-package json-mode
  :mode
  ("\\.babelrc\\'"
   "\\.browserslistrc\\'"
   "\\.eslintrc\\'"
   "\\.prettierrc\\'"
   "\\.tslintrc\\'")
  ;; :hook (json-mode . #'my-bind-prettier-js)
)
#+end_src

** YAML

#+begin_src emacs-lisp
(use-package yaml-mode
  :mode ("\\.yml\\'" "\\.yaml\\'"))
#+end_src

** Markdown

Use =Github Flavored Markdown= for markdown files. It provides tons of functionalities. Check [[https://jblevins.org/projects/markdown-mode/][the document]].

#+begin_src emacs-lisp
(use-package markdown-mode
  :commands (markdown-mode gfm-mode)
  :mode (("\\.md\\'"  . gfm-mode)
         ("\\.markdown\\'"  . gfm-mode))
  :init
  (setq markdown-list-indent-width 2
        markdown-hide-urls t
        markdown-gfm-use-electric-backquote nil)
  :config
  ;; (setq markdown-open-command "/usr/bin/marked") ; I don't use marked anymore. I need to find a replacement.
  (setq markdown-command "pandoc --standalone --mathjax --from=markdown"))
#+end_src

** CSV

#+begin_src emacs-lisp
(use-package csv-mode
  :commands (csv-mode)
  :mode (("\\.csv\\'"  . csv-mode)))
#+end_src

* org

** Install

Install org from elpa

#+begin_src emacs-lisp
(use-package org
  :ensure org-plus-contrib)
#+end_src

** Display Preference

Set header line faces.

#+begin_src emacs-lisp
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.1))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.1))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.1))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.1))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.1)))))
#+end_src

=org-indent-mode= is clean and less-fancy/less-distracting.

#+begin_src emacs-lisp
(setq org-startup-indented t)
#+end_src

Turn on wordwarp.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook #'visual-line-mode)
#+end_src

** Code Block

Use current window for the src editing.

#+begin_src emacs-lisp
(setq org-src-window-setup 'current-window)
#+end_src

Prefer no indentation in the =src= block.

#+begin_src emacs-lisp
(setq org-edit-src-content-indentation 0)
#+end_src

=[TAB]= should works as same as the language specific mode.

#+begin_src emacs-lisp
(setq org-src-tab-acts-natively t)
#+end_src

Activate languages for Babel. Only =emacs-lisp= is activated in default. The available languages are listed on [[https://orgmode.org/manual/Languages.html][here]].

#+begin_src emacs-lisp
(use-package ob-restclient)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((js . t)
   (python . t)
   (restclient . t)))
#+end_src

Do not ask me to confirm evaluation for any languages.

#+begin_src emacs-lisp
(setq org-confirm-babel-evaluate nil)
#+end_src

Default JS template has a problem to run on newer version of =Node.js=. To fix it, replace the template code. /I've only checked on v12.10.0/

#+begin_src emacs-lisp
(setq org-babel-js-function-wrapper
      "process.stdout.write(
  require('util').inspect((() => {
    %s
  })(), { depth: null, compact: true })
)")
#+end_src

Add structure templates for languages which frequently used.

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("js" . "src js"))
(add-to-list 'org-structure-template-alist '("rest" . "src restclient"))
#+end_src

** Task Management

Track when a TODO was maked as =DONE=.

#+begin_src emacs-lisp
(setq org-log-done t)
(setq calendar-week-start-day 1)
#+end_src

** Agenda

#+begin_src emacs-lisp
(setq org-agenda-files (directory-files-recursively "~/org/" "\\.org$"))
#+end_src

** Export

Use =ox-hugo= as a exportar for Markdown. (You can use ~org-blackfriday-export-as-markdown~ for plain markdown exportation without front-matter.) For the other format, =pandoc= does a grate job!

#+begin_src emacs-lisp
;; (require 'ox-md)
(use-package ox-hugo :after ox)
(use-package ox-pandoc :after ox :disabled)
#+end_src

** Misc

Enable alphabetical lists.

#+begin_src emacs-lisp
(setq org-list-allow-alphabetical t)
#+end_src

** Capture

TBD


* Other Utilities
** Scratch
=M-x scratch= to create a scratch buffer with the current =major-mode=. =C-u M-x scratch= propmpts you to choose the mode.

#+begin_src emacs-lisp
(use-package scratch
  :commands scratch
  :bind ("<f12>" . scratch))
#+end_src
