# Espanso configuration file
# see official doc for available options
# → https://espanso.org/docs/configuration/options/
# edit match/*.yml for expansion

toggle_key: off
auto_restart: true
search_shortcut: off
search_trigger: ";esp"
show_icon: false
