[settings]
verbose = false

minimum_release_age = "7d"

idiomatic_version_file_enable_tools = [
  "python",    # .python-version, .python-versions
  "node",      # .nvmrc, .node-version, package.json
  "pnpm",      # package.json
  "npm",       # package.json
  "yarn",      # .yvmrc, package.json
  "deno",      # .deno-version, package.json
  "bun",       # .bun-version, package.json
  "terraform", # .terraform-version
  "go",        # .go-version
  "java",      # .java-version, .sdkmanrc
  "ruby",      # .ruby-version, Gemfile
  "perl",      # .perl-version
  "rust",      # rust-toolchain.toml
]

python.uv_venv_auto = "source"
