#!/bin/sh
#
# pre-commit hook script to check local configuration.
# abort commit if "user.name" or "user.email" is missed.

CONFIGURED=1

if [ -z "`git config --local user.name`" ]; then
    echo "\"user.name\" is missed."
    echo "git config --local user.name"
    CONFIGURED=0
fi

if [ -z "`git config --local user.email`" ]; then
    echo "\"user.email\" is missed."
    echo "git config --local user.email"
    CONFIGURED=0
fi

if [ $CONFIGURED -eq 0 ]; then
    exit 1
fi
