# Dev related replacements

matches:
  # Network
  - trigger: ";ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "dig -4 +short @resolver1.opendns.com ANY myip.opendns.com"

  # Network
  - trigger: ";6ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "dig -6 +short @resolver1.opendns.com ANY myip.opendns.com"

  # Markdown
  - trigger: ";details"
    replace: >
      <details> 
      <summary>SQL</summary> 
      
      ``` 
      ``` 
      
      </details>

  # Lorem Ipsum
  - trigger: ";lorem"
    replace: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui eius, voluptate quisquam impedit repudiandae earum laborum quasi ipsa numquam aliquam, blanditiis ut fuga voluptatibus rem voluptas in tempora vero aut.
  - trigger: ";ipsum"
    replace: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui eius, voluptate quisquam impedit repudiandae earum laborum quasi ipsa numquam aliquam, blanditiis ut fuga voluptatibus rem voluptas in tempora vero aut.

